### ISSUE TITLE
Adaptar taller en la rama feature/cfp_2014

### ISSUE THREAD

**Issue by jsanz** [geoinquietosvlc/mapproxy-workshop#4]
He creado la rama feature/cfp_2014 a partir de la rama de siglibre8.

Hay que cambiar los logos y textos relativos al taller de Girona como primera tarea para esta edición.

**Comment by jsanz** [comment]
Por cierto @vehrka, ya está dada de alta la versión en el RTD en

https://mapproxy-workshop.readthedocs.org/es/feature-cfp_2014/

**Comment by vehrka** [comment]
Actualizada la entrada con una breve descripción del taller y el logo de MapProxy.

Metida una referencia a geoinquietos

Creada la URL de bit.ly para apuntar a la rama de readthedocs

**Comment by vehrka** [comment]
Por cierto... ¿vamos a adaptar los ejercicios a Valencia en vez de Girona?

Bo, te igual, mañana hablamos con tranquilidad de los siguientes pasos.

Au!

**Comment by jsanz** [comment]
Creada la issue y metida en el "por hacer" del kanban del huboard

**Comment by jsanz** [comment]
Pendiente de revisar, doy la tarea por terminada (sin cerrar)
